- name: Docker Configure in GCP VM-Machine
  hosts: all
  become: true
  connection: ssh
  tasks:
  - name: Updating the New VM machine
    command: sudo apt update -y

  - name: Install Docker
    command: sudo apt-get install docker.io -y
    become: yes
    become_user: root

  - name: Start Docker service
    command: sudo systemctl start docker
    become: yes
    become_user: root

  - name: Deploy the Image and Run as Container
    command: docker run -itd -p 8084:8081 sharishankar43/insure_me_app:1.0
